### ISSUE TITLE
Set up CI testing 🧪

### ISSUE THREAD

**Issue by gutenfries** [dart-sys/dart-sys#10]
# Set up CI tests 🧪

## Tasks: 
- [x] Set up CI for:
	- [ ] Integration tests
	- [x] Unit tests
	- [x] Mock (spec) tests
	- [ ] Code examples
- [x] Implement platform matrix testing

**Comment by gutenfries** [comment]
improved in #25

**Comment by gutenfries** [comment]
completed with #40
