### ISSUE TITLE
Update Examples 🧑‍🏫

### ISSUE THREAD

**Issue by gutenfries** [dart-sys/dart-sys#11]
# Update Examples 🧑‍🏫

## Tasks:
- [ ] Update existing examples
- [ ] Write more examples
	- [ ] Multi-threading
	- [ ] Async suspension/deferment
	- [ ] Example with vanilla dart code
	- [ ] Example with flutter
	- [ ] Async management with flutter
- [ ] Document examples verbosely

**Comment by gutenfries** [comment]
worked on in #44
