### ISSUE TITLE
Set up `bindgen` in build.rs ⚙️

### ISSUE THREAD

**Issue by gutenfries** [dart-sys/dart-sys#9]
# Set up `bindgen` in build.rs ⚙️

## Tasks:

- [ ] Upgrade `bindgen` to the latest LTS release in cargo.toml.
- [ ] Set up `bindgen` in build.rs to generate bindings.
	- [ ] By default, auto-load the dart-SDK C++ headers over HTTPS.
	- [x] Package latest dart SDK C++ headers with the repository as a fallback if `cfg(no-net)` is true.
	- [ ] ensure code is compliant with `cfg(no-std)` (overloads are OK.).

**Comment by gutenfries** [comment]
linked development branch: https://github.com/dart-sys/dart-sys/tree/(feat/enhancement)-set-up-bindgen-%239
